---
title: "week_01_assign_01"
author: "ashraf.said@etu.unige.ch"
date: "`r Sys.Date()`"
output: html_document
---
1- Create a vector called weight containing the weight (in kg) of 10 children: $69,62,57,59,59,64,56,66,67,66$
```{r}
weight_child <- c(69,62,57,59,59,64,56,66,67,66)
weight_child
```
2- Extracting elements from within the vector above and doing summary statistics

```{r cars}
weight_child[1]
first_five_elements <- weight_child[1:5];first_five_elements
summary(weight_child) ;sd(weight_child)
```
3- Importing data files and displaying the first few rows
```{r}
LastCall1.data <- read.table("C:\\Users\\JEmre\\Downloads\\LastCall1.txt")
head(LastCall1.data)
```

```{r}
data <- read.csv2("C:\\Users\\JEmre\\Downloads\\LastCall4.csv",sep = ",", header = F)
head(data)
```
```{r}
last_call_2 <- read.table("C:\\Users\\JEmre\\Downloads\\LastCall2.txt", header = T)
head(last_call_2)
```

```{r}
last_call_2$male
last_call_2$female
```


```{r}
m<- mean(last_call_2$male)
m ; summary(m)
```
```{r}
f<- mean(last_call_2$female)
f ; summary(f)
```


